`r opts_chunk$set(cache=FALSE, echo=FALSE)`

# Bacterial communities on classroom surfaces

## Manuscript demo

_James F Meadow_^1^

^1^ Biology and the Built Environment Center, Institute of Ecology and Evolution, University of Oregon, Eugene, OR USA, jfmeadow@gmail.com

-------------------

### Introduction

The data used here are a small subset (first 20,000 quality-filtered sequences) of those previously published [@meadowSurfaces2014]. This demo illustrates a few basic multivariate analysis methods with a sample dataset. In the original manuscript, we investigated the sources of microbes on classroom surfaces, and whether those microbial communities reflect common human contact with indoor surfaces. 

### Methods

This sequence dataset was processed using QIIME 1.8 [@qiime] with a default MacQIIME installation ([http://www.wernerlab.org/software/macqiime](http://www.wernerlab.org/software/macqiime)). Scripts for processing raw data are in the `../QIIME/` folder. To pick OTUs in that folder, you will execute the `pickTheseOTUs.sh` script sitting in that folder. This script wants to run MacQIIME, so if you are not using MacQIIME, you'll probably need to alter the top line. For statistical analyses, we primiarily used the `phyloseq` package to handle QIIME output files, and `vegan` and `labdsv` for multivariate ecology stats [@phyloseq; @vegan; @labdsv]. All sequences were rarefied to an equal sampling depth (100 sequences per sample) prior to analysis. Beta-diversity was calculated using the Canberra taxonomic metric. Reproducible documents were created with the `knitr` package in R [@knitr].

```{r setSeed}
# setwd('~/Dropbox/SLP_Teaching/manuscriptRmd')
set.seed(42)
```

```{r loadPackages, message=FALSE}
library(knitr)
library(phyloseq)
library(vegan)
library(labdsv)
library(xtable)
```

```{r importPhyloseq}
surfaceTablePhyloseq <- import_biom('../QIIME/otu_table.biom', 
                                    parseFunction=parse_taxonomy_greengenes)
surfaceMapPhyloseq <- import_qiime_sample_data('../QIIME/map.txt')
```

```{r extractOTUtable}
surfaceTable.tmp <- t(otu_table(surfaceTablePhyloseq))
surfaceTable.tmp <- surfaceTable.tmp[!(row.names(surfaceTable.tmp) =='Swab.162.61'), ]
surfaceTable <- as(surfaceTable.tmp, 'matrix')
# surfaceTable[1:5, 1:5]
```

```{r extractMap}
surfaceMap <- data.frame(surfaceMapPhyloseq)[-1, ]
# head(surfaceMap)
```

```{r extractTaxa}
surfaceTaxa <- data.frame(tax_table(surfaceTablePhyloseq))
for (i in 1:ncol(surfaceTaxa)) {
  surfaceTaxa[, i] <- as.character(surfaceTaxa[, i])
  surfaceTaxa[, i][is.na(surfaceTaxa[, i])] <- '-'
  }
# kable(data.frame(head(surfaceTaxa)[, c(2, 5:7)]))
```

```{r testTaxa}
# identical(row.names(surfaceTaxa), colnames(surfaceTable))
```

```{r testSampleID}
# identical(sort(row.names(surfaceMap)), sort(row.names(surfaceTable)))
```

```{r removeUnwanted, echo=FALSE, eval=TRUE}
# dim(surfaceTaxa)
surfaceTaxa <- surfaceTaxa[-c(grep('mitochondria', surfaceTaxa$Family)), ]
surfaceTaxa <- surfaceTaxa[-c(grep('Chloroplast', surfaceTaxa$Class)), ]
surfaceTable <- surfaceTable[, row.names(surfaceTaxa)]
# identical(row.names(surfaceTaxa), colnames(surfaceTable))
# dim(surfaceTaxa)
```

```{r checkSampleSum}
# sort(rowSums(surfaceTable), decreasing=FALSE)
```

```{r rarefy100}
surfaceTable <- surfaceTable[which(rowSums(surfaceTable) > 100), ]
tab <- rrarefy(surfaceTable, 100)
```

```{r mapColors}
map <- surfaceMap[row.names(tab), ]
map$color <- 'wheat'
map$color[map$SurfaceType == 'floor'] <- 'chocolate3'
map$color[map$SurfaceType == 'chair'] <- 'darkslateblue'
map$color[map$SurfaceType == 'desk'] <- 'goldenrod3'
map$SurfaceType <- factor(map$SurfaceType, levels=c("wall", "floor",  "chair", "desk"))
```

```{r sortBySortID}
names(map)[1] <- gsub('X.', '', names(map)[1])

map$sortID <- as.character(map$SampleID)
for(i in 1:nrow(map)) {
  if(nchar(map$sortID[i]) == 10) {
    map$sortID[i] <- gsub('162.', '162.0', map$sortID[i])
  }
}

map <- map[order(map$sortID), 
           c('sortID', 'SurfaceType', 'xcoord', 'ycoord', 'color')]
```

```{r reconcileTable}
tab <- tab[row.names(map), which(colSums(tab) > 0)]
taxa <- surfaceTaxa[colnames(tab), ]
# head(taxa)
# dim(taxa)
```


```{r createDistance}
distCanberra <- vegdist(tab, 'canberra')
```

```{r makeNMDS, results='hide'}
nmdsCanberra <- bestnmds(distCanberra)
```

```{r mostAbundantOTU}
mostAbu <- names(sort(colSums(tab), TRUE)[1])
# taxa[mostAbu, ]
```

### Results

Out of a total `r sum(surfaceTable)` sequences that passed quality filtering, we analyzed `r sum(tab)` sequences in `r nrow(tab)` samples distributed among `r ncol(tab)` OTUs (97% sequence similarity). The most abundant OTU in the dataset was a Cyanobacterium (`r round(100*(sum(tab[, mostAbu])/sum(tab)), 2)`% of all sequences). The most abundant taxa are shown in Table 1. \pagebreak

```{r mostAbundant, results='asis', }
tops <- names(sort(colSums(tab), decreasing=TRUE)[1:5])
topTaxa <- taxa[tops, c(2, 5:7)]
topTaxa$RelAbu <- colSums(tab)[tops]/100
# print(xtable(topTaxa))  # a way to make better LaTeX tables with more options
kable(topTaxa)  # quick way to make markdown tables that will convert to LaTeX
```

```{r plotNMDS, fig.width=6, fig.height=5, fig.cap='Samples cluster by the type of surface.'}
par(mar=c(5,4,1,5), las=1, xpd=TRUE)
plot(nmdsCanberra, pch=21, cex=2, bg=map$color)
legend(par()$usr[2], par()$usr[4], pch=21, pt.cex=1.5,
       legend=levels(map$SurfaceType), 
       pt.bg=unique(map$color), bty='n')
```


```{r surfaceTypeModel, results='asis'}
surfaceTypeModel <- adonis(distCanberra ~ map$SurfaceType)$aov.tab
# names(surfaceTypeModel)
# print(xtable(surfaceTypeModel))
# surfaceTypeModel
surfaceTypeModel[is.na(surfaceTypeModel)] <- ''
kable(surfaceTypeModel)
```


We found that surface type explained a significant amount of community variation (p = `r surfaceTypeModel[1, 'Pr(>F)']`; from PERMANOVA on Canberra distances). 


Next, we tested for a quasi-distance-decay relationship. This is the sort of pattern we see in just about every ecosystem with most forms of life. We even found this to be a stong predictor in the dust sampled from the entire building [@KembelPLOS2014]. So we can use the x and y coordinates as a map of samples, and then calculate the Euclidean pairwise distance between all samples. Then that goes through a mantel test to determine if these distance are correlated with the community distances. 

```{r spatialMantel}
distSpatial <- dist(data.frame(map$xcoor, map$ycoor))
mantelTable <- mantel(distCanberra, distSpatial)
# names(mantelTable)
```

```{r testMantelTypes}
chair <- which(map$SurfaceType == 'chair')
wall <- which(map$SurfaceType == 'wall')
desk <- which(map$SurfaceType == 'desk')
floor <- which(map$SurfaceType == 'floor')

testMantel <- function(these) {
  mantel(vegdist(tab[these, ], 'canberra'), 
                 dist(data.frame(map$xcoor, map$ycoor)[these, ]))
  }

# testMantel(chair)
# testMantel(wall)
# testMantel(desk)
# testMantel(floor)
```

We did not find any significant coorelation between community similarity and spatial distance (p = `r mantelTable$signif`; from Mantel test) when considering all samples together. Likewise, individual sample types tested alone showed no relationship with spatial distance (p > 0.1 for all four sample types). 


### Discussion

So it looks like the type of surface, potentially as a proxy for human contact, explains a significant amount of variation, in the microbial communities on those surfaces, but their proximity to each other around the room doesn't seem to matter at all. 



----------------

### References